services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sidaroco
      POSTGRES_PASSWORD: sidaroco
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  authentication-service:
    build:
      context: .
      dockerfile: services/authenticationService/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/authenticationService/.env
    environment:
      AUTH_SERVICE_PORT: 3000
      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key
      CORS_DOMAIN: www.sidaroco.com
      DATABASE_URL: postgresql://sidaroco:sidaroco@postgres:5432/auth_db?schema=public
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./packages/keys:/keys:ro


  fleet-service:
    build:
      context: .
      dockerfile: services/fleet-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/fleet-service/.env
    environment:
      FLEET_SERVICE_PORT: 3001    
      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key
      DATABASE_URL: postgresql://sidaroco:sidaroco@postgres:5432/sidaroco_fleet
      AUTH_SERVICE_URL: http://authentication-service:3000
      ROUTE_SERVICE_URL: http://route-service:3003
      CORS_DOMAIN: www.sidaroco.com

    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./packages/keys:/keys:ro


  mail-service:
    build:
      context: .
      dockerfile: services/mail-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/mail-service/.env
    environment:
      MAIL_SERVICE_PORT: 3002
      CORS_DOMAIN: www.sidaroco.com
    ports:
      - "3002:3002"
    volumes:
      - ./packages/keys:/keys:ro

  route-service:
    build:
      context: .
      dockerfile: services/route-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/route-service/.env
    environment:
      ROUTE_SERVICE_PORT: 3003
      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key
      DATABASE_URL: postgresql://sidaroco:sidaroco@postgres:5432/sidaroco_route
      AUTH_SERVICE_URL: http://authentication-service:3000
      CORS_DOMAIN: www.sidaroco.com
    depends_on:
      - postgres
    ports:
      - "3003:3003"
    volumes:
      - ./packages/keys:/keys:ro

  ticket-service:
    build:
      context: .
      dockerfile: services/ticket-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/ticket-service/.env
    environment:
      TICKET_SERVICE_PORT: 3004
      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key
      SCHEDULE_SERVICE_URL: http://schedule-service:3006
      DATABASE_URL: postgresql://sidaroco:sidaroco@postgres:5432/sidaroco_ticket
      AUTH_SERVICE_URL: http://authentication-service:3000
      CORS_DOMAIN: www.sidaroco.com
      MAIL_SERVICE_URL: http://mail-service:3002
      USERS_SERVICE_URL: http://users-service:3005
    depends_on:
      - postgres
    ports:
      - "3004:3004"
    volumes:
      - ./packages/keys:/keys:ro

  users-service:
    build:
      context: .
      dockerfile: services/users-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/users-service/.env
    environment:
      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key
      USERS_SERVICE_PORT: 3005
      DATABASE_URL: postgresql://sidaroco:sidaroco@postgres:5432/users_db?schema=public
      AUTH_SERVICE_URL: http://authentication-service:3000
      MAIL_SERVICE_URL: http://mail-service:3002
      CORS_DOMAIN: www.sidaroco.com
    depends_on:
      - postgres
      - authentication-service
    ports:
      - "3005:3005"
    volumes: 
      - ./packages/keys:/keys:ro
  
  schedule-service:
    build:
      context: .
      dockerfile: services/schedule-service/Dockerfile
    restart: unless-stopped
    env_file:
      - ./services/schedule-service/.env
    environment:
      SCHEDULE_SERVICE_PORT: 3006
      JWT_PRIVATE_KEY_PATH: /keys/private.key
      JWT_PUBLIC_KEY_PATH: /keys/public.key
      DATABASE_URL: postgresql://sidaroco:sidaroco@postgres:5432/sidaroco_schedule
      AUTH_SERVICE_URL: http://authentication-service:3000
      ROUTE_SERVICE_URL: http://route-service:3003
      FLEET_SERVICE_URL: http://fleet-service:3001
      TICKET_SERVICE_URL: http://ticket-service:3004
      CORS_DOMAIN: www.sidaroco.com
    depends_on:
      - postgres
    ports:
      - "3006:3006"
    volumes:
      - ./packages/keys:/keys:ro

    

volumes:
  postgres_data:
